version: '3'
services:
  my-app:
    image: my-app:1.0 #app508deploycr.azurecr.io/alexey/my-app:1.1
    ports:
      - 3001:3001
    container_name: docker-first-app
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    container_name: docker-first-mongodb
  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    container_name: docker-first-mongo-express
volumes:
  mongo-data:
    driver: local
